<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('Source')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_Source.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('Source.so')) return;
    } else {
      if (!dl('Source.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class Source {
	static function add_button($label,$x,$y) {
		add_button($label,$x,$y);
	}

	static function add_check_button($label,$x,$y) {
		add_check_button($label,$x,$y);
	}

	static function add_entry($defaultText,$x,$y) {
		add_entry($defaultText,$x,$y);
	}

	static function show_message_box($title,$message) {
		show_message_box($title,$message);
	}

	static function add_menu_bar() {
		add_menu_bar();
	}

	static function add_radio() {
		add_radio();
	}

	static function add_link_button($link,$label,$x,$y) {
		add_link_button($link,$label,$x,$y);
	}

	static function add_switch($active,$x,$y) {
		add_switch($active,$x,$y);
	}

	static function add_label($text,$x,$y) {
		add_label($text,$x,$y);
	}

	static function add_image($file,$x,$y) {
		add_image($file,$x,$y);
	}

	static function start($title,$width,$height) {
		return start($title,$width,$height);
	}
}

/* PHP Proxy Classes */

